### ISSUE TITLE
GitとGithubを理解する

### ISSUE THREAD

**Issue by tsukumon** [tsukumon/kbc-chat#5]
以下のチュートリアルの入門編、発展編（チュートリアル２まで）、プルリクエストを通読する
https://backlog.com/ja/git-tutorial/

または、一通りのgitを理解し使えることができるようになる

注意: ブランチ命名規則は設けませんが、ブランチ名を見ただけである程度ブランチの内容が理解できるようにしてくれたら助かります

**Comment by w-record** [comment]
必要ないかとも思いましたが、復習のためにもう一度目を通しました。

**Comment by tsukumon** [comment]
> 必要ないかとも思いましたが、復習のためにもう一度目を通しました。

ありがとうございます！

**Comment by freetaso** [comment]
hello

**Comment by freetaso** [comment]
たけうちに書き込めって脅されました。
もう震えが止まりません...
