### ISSUE TITLE
Rubyを理解する

### ISSUE THREAD

**Issue by tsukumon** [tsukumon/kbc-chat#6]
Rubyで以下の内容を理解する  
学習に使う媒体は各自に任せます  

```
・変数（必須）
・配列（必須）
・関数 メソッド（必須）
・引数（必須）
・戻り値（必須）
・条件分岐（必須）
・繰り返し（必須）
・クラス（推奨）
・オブジェクト（できれば。理解だけでもいい）
・正規表現（必須）
```

今後、ユーザー管理やDB操作で正規表現は頻繁に使うので必須でお願いします。
（参考資料）  
https://qiita.com/agotoh/items/87960d256e427d5673a9
https://qiita.com/jnchito/items/893c887fbf19e17d3ff9

**Comment by w-record** [comment]
スタンプ押したけどわかりずらいと思ったので、やりましたコメントのこします。

**Comment by freetaso** [comment]
一応ここも。
